apiVersion: v2
name: SAP_CAP
description: A simple CAP project.
type: application
version: 1.0.0
appVersion: 1.0.0
annotations:
  app.kubernetes.io/managed-by: cds-dk/helm
dependencies:
  - name: web-application
    alias: srv
    version: ">0.0.0"
  - name: web-application
    alias: sidecar
    version: ">0.0.0"
  - name: service-instance
    alias: saas-registry
    version: ">0.0.0"
  - name: service-instance
    alias: service-manager
    version: ">0.0.0"
