---
spring:
  config.activate.on-profile: default
  sql.init.platform: h2
  web.resources.static-locations: "file:./app"
  security:
    basic:
      enabled: true
    user:
      name: admin
      password: admin
      roles: admin
cds:
  data-source.auto-config.enabled: false
  odata-v4:
    endpoint:
      path: /api
    version: v4
    protocol: odata
